docs | добавлены чистый txt файл с данными и json файл с парами вопрос-ответ
QQQiwi/student-qa-bot pull request #3
Opened 2024-09-27 12:00 UTC by FredMove

txt файл был опорой для создания json'a. Проверить на счетчик говна в json

2024-10-11 21:58 UTC, QQQiwi requested changes
Попрошу:

1. Всё завернуть в отдельную директорию (например `data`)
2. Вместо документа формата docx лучше загрузить его txt-версию. С ней будет проще работать.
3. Лучше всё писать в одном регистре. Т.е. вместо **Guide_data.json** -> **guide_data.json**.

2024-10-11 21:58 UTC, QQQiwi commented on Guide_data.json
> +    {
Что это за JSON такой, что его загрузить нельзя?)

Тут лишняя скобка на 98-й строке.

2024-10-11 21:58 UTC, QQQiwi commented on Guide_data.json
> +	},
Лишняя запятая, из-за неё тоже JSON нельзя считать

2024-10-13 04:56 UTC, FredMove commented
дело сделано

2024-10-13 23:44 UTC, QQQiwi approved these changes

2024-10-13 23:44 UTC, QQQiwi commented
LGTM, можно мерджить

2025-03-10 17:22 UTC, merged